language: python
python:
  - '3.8'
services:
  - docker
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install bandit
script:
  - bandit -r .
  - docker build -t asp-02 .
  - docker run -d -p 5000:5000 asp-02
  - sleep 3
  - curl -s http://localhost:5000 | grep "Valor 1"
  - ngrok http 5000 &
  - sleep 10
  - curl -s http://localhost:4040/api/tunnels | grep -o "https://.*\.ngrok.io" > ngrok_url.txt
  - open ngrok_url.txt
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

after_success:
  - ls
  - bash ./telegram_notifications.sh
