language: python
python:
  - '3.8'
services:
  - docker
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install bandit
  - wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip ngrok-stable-linux-amd64.zip
  - pip install ngrok
  - curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
  sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
  echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
  sudo tee /etc/apt/sources.list.d/ngrok.list && \
  sudo apt update && sudo apt install ngrok
script:
  - bandit -r .
  - docker build -t asp-02 .
  - docker run -d -p 5000:5000 asp-02
  - sleep 3
  - curl -s http://localhost:5000 | grep "Valor 1"
  - chmod +x ngrok
  - ngrok config add-authtoken 2NnGzzQUH9cESqpCLO8vqhsQI2U_7dzrU175WK3ecos29PsAV
  - ngrok http 5000 &
  - sleep 10
  - curl -s http://localhost:4040/api/tunnels | grep -o "https://.*\.ngrok.io" > ngrok_url.txt
  - open ngrok_url.txt
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

after_success:
  - ls
  - bash ./telegram_notifications.sh
